### ISSUE TITLE
nginx discovery duplicates bindings

### ISSUE THREAD

**Issue by adrianlzt** [datadope-io/ansible_collection_discovery#17]
When an nginx software is discovered, the returning ``bindings`` list has the same entries repeated:

```
  nginx_monitor__swfacts:
  - code: nginx..nginx__80
    description: nginx nginx 80
    facts:
      bindings:
      - address: 0.0.0.0
        class: service
        extra_data:
          protocol: http
          status: '200'
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        extra_data:
          protocol: http
          status: '403'
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
      - address: 0.0.0.0
        class: service
        port: 80
        protocol: tcp
      - address: '::'
        class: service
        port: 80
        protocol: tcp
```
